/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BusinessSlugRouteImport } from './routes/$businessSlug'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminReportsIndexRouteImport } from './routes/admin/reports/index'
import { Route as AdminEmployeesIndexRouteImport } from './routes/admin/employees/index'
import { Route as AdminBusinessesIndexRouteImport } from './routes/admin/businesses/index'
import { Route as AdminAttendanceIndexRouteImport } from './routes/admin/attendance/index'
import { Route as AdminEmployeesNewRouteImport } from './routes/admin/employees/new'
import { Route as AdminBusinessesNewRouteImport } from './routes/admin/businesses/new'

const BusinessSlugRoute = BusinessSlugRouteImport.update({
  id: '/$businessSlug',
  path: '/$businessSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsIndexRoute = AdminReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmployeesIndexRoute = AdminEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBusinessesIndexRoute = AdminBusinessesIndexRouteImport.update({
  id: '/businesses/',
  path: '/businesses/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAttendanceIndexRoute = AdminAttendanceIndexRouteImport.update({
  id: '/attendance/',
  path: '/attendance/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmployeesNewRoute = AdminEmployeesNewRouteImport.update({
  id: '/employees/new',
  path: '/employees/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBusinessesNewRoute = AdminBusinessesNewRouteImport.update({
  id: '/businesses/new',
  path: '/businesses/new',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$businessSlug': typeof BusinessSlugRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/businesses/new': typeof AdminBusinessesNewRoute
  '/admin/employees/new': typeof AdminEmployeesNewRoute
  '/admin/attendance/': typeof AdminAttendanceIndexRoute
  '/admin/businesses/': typeof AdminBusinessesIndexRoute
  '/admin/employees/': typeof AdminEmployeesIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$businessSlug': typeof BusinessSlugRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/businesses/new': typeof AdminBusinessesNewRoute
  '/admin/employees/new': typeof AdminEmployeesNewRoute
  '/admin/attendance': typeof AdminAttendanceIndexRoute
  '/admin/businesses': typeof AdminBusinessesIndexRoute
  '/admin/employees': typeof AdminEmployeesIndexRoute
  '/admin/reports': typeof AdminReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$businessSlug': typeof BusinessSlugRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/businesses/new': typeof AdminBusinessesNewRoute
  '/admin/employees/new': typeof AdminEmployeesNewRoute
  '/admin/attendance/': typeof AdminAttendanceIndexRoute
  '/admin/businesses/': typeof AdminBusinessesIndexRoute
  '/admin/employees/': typeof AdminEmployeesIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/$businessSlug'
    | '/admin/login'
    | '/admin/'
    | '/admin/businesses/new'
    | '/admin/employees/new'
    | '/admin/attendance/'
    | '/admin/businesses/'
    | '/admin/employees/'
    | '/admin/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$businessSlug'
    | '/admin/login'
    | '/admin'
    | '/admin/businesses/new'
    | '/admin/employees/new'
    | '/admin/attendance'
    | '/admin/businesses'
    | '/admin/employees'
    | '/admin/reports'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/$businessSlug'
    | '/admin/login'
    | '/admin/'
    | '/admin/businesses/new'
    | '/admin/employees/new'
    | '/admin/attendance/'
    | '/admin/businesses/'
    | '/admin/employees/'
    | '/admin/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  BusinessSlugRoute: typeof BusinessSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$businessSlug': {
      id: '/$businessSlug'
      path: '/$businessSlug'
      fullPath: '/$businessSlug'
      preLoaderRoute: typeof BusinessSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports/': {
      id: '/admin/reports/'
      path: '/reports'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof AdminReportsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/employees/': {
      id: '/admin/employees/'
      path: '/employees'
      fullPath: '/admin/employees/'
      preLoaderRoute: typeof AdminEmployeesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/businesses/': {
      id: '/admin/businesses/'
      path: '/businesses'
      fullPath: '/admin/businesses/'
      preLoaderRoute: typeof AdminBusinessesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/attendance/': {
      id: '/admin/attendance/'
      path: '/attendance'
      fullPath: '/admin/attendance/'
      preLoaderRoute: typeof AdminAttendanceIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/employees/new': {
      id: '/admin/employees/new'
      path: '/employees/new'
      fullPath: '/admin/employees/new'
      preLoaderRoute: typeof AdminEmployeesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/businesses/new': {
      id: '/admin/businesses/new'
      path: '/businesses/new'
      fullPath: '/admin/businesses/new'
      preLoaderRoute: typeof AdminBusinessesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBusinessesNewRoute: typeof AdminBusinessesNewRoute
  AdminEmployeesNewRoute: typeof AdminEmployeesNewRoute
  AdminAttendanceIndexRoute: typeof AdminAttendanceIndexRoute
  AdminBusinessesIndexRoute: typeof AdminBusinessesIndexRoute
  AdminEmployeesIndexRoute: typeof AdminEmployeesIndexRoute
  AdminReportsIndexRoute: typeof AdminReportsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBusinessesNewRoute: AdminBusinessesNewRoute,
  AdminEmployeesNewRoute: AdminEmployeesNewRoute,
  AdminAttendanceIndexRoute: AdminAttendanceIndexRoute,
  AdminBusinessesIndexRoute: AdminBusinessesIndexRoute,
  AdminEmployeesIndexRoute: AdminEmployeesIndexRoute,
  AdminReportsIndexRoute: AdminReportsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  BusinessSlugRoute: BusinessSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
